### ISSUE TITLE
Add sections to About Page

### ISSUE THREAD

**Issue by CynCity098** [JenniferLarsen/TW-Course-2#12]
> “mission” hero section

> “who are we” : ImPastas/ Team 2 from Techwise cohort II students Supported by Google

> individual highlights: name, photo, school, major, “personal motto,” contact pages (ig, LinkedIn, GitHub)

> Inspirational quote from Gordon Ramsey

**Comment by mabe3069** [comment]
This is almost finished except for some more details about our members.

**Comment by mabe3069** [comment]
This has been completed.

**Comment by mabe3069** [comment]
This has been completed
